### ISSUE TITLE
Opening settings causes discord to crash

### ISSUE THREAD

**Issue by Kumicoo** [YofukashiNo/FakeDeafen#6]
Not sure how to even use this if i cant open the settings, is there a keybing or something

**Comment by YofukashiNo** [comment]
you can open settings??

**Comment by Kumicoo** [comment]
What? Yeah, but it sometimes crashes, any idea? 
![image](https://github.com/YofukashiNo/FakeDeafen/assets/35538818/f4ff9c8a-c267-4e56-ae39-cbdd604401e3)

**Comment by FlipFlopInteractive** [comment]
yep is broken, new update just fucked it up, discord crashes when loading it, if you could patch I would be glad uwu

**Comment by Awooochy** [comment]
yep new update broke it, crashes on load, if you could patch it please uwu

**Comment by YofukashiNo** [comment]
can't replicate?

**Comment by Awooochy** [comment]
yes, basically crashes on start BUT if in settings you disable the UI (The buttons in the main discord tab, and just use it from settings it works and doesn't crash, but is annoying to have to open the settings for every time I gotta use it.

**Comment by Awooochy** [comment]
If it works for you it could be related to custom replugged backgrounds, (I'm using: Dis-Cons, Expresso, and Oneko Animation)

**Comment by YofukashiNo** [comment]
you meant his https://github.com/YofukashiNo/FakeDeafen/issues/5
